### ISSUE TITLE
My partner wants to use this and i am scared

### ISSUE THREAD

**Issue by B2H990** [vialdevelopment/guerrilla#5]
Please delete the repo to solve this issue

**Comment by SWP360** [comment]
please delete this asap

**Comment by ghost** [comment]
don't be scared
simple

**Comment by ghost** [comment]
@charlie353535 please resolve this internal conflict

**Comment by SWP360** [comment]
I see nothing wrong with this! Make sure to use Guerrilla for free this week!

**Comment by SWP360** [comment]
![photo](https://user-images.githubusercontent.com/44510312/107421040-cf3a7000-6b19-11eb-94f9-e0f7d88d7bb1.png)
Hey.

**Comment by B2H990** [comment]
( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡° ) ͜ʖ ͡°) ͡°)

**Comment by B2H990** [comment]
⎝ ⏠⏝⏠⎠

**Comment by ghost** [comment]
Now, A2H, why do you feel that you are being "forced" to use this, rather than have the pleasure to?

**Comment by SWP360** [comment]
![photo](https://user-images.githubusercontent.com/44510312/107421058-d5305100-6b19-11eb-8fcf-8e07fb7e76a6.png)
You can't silence me :)
I'll always be lurking around.

**Comment by SWP360** [comment]
![photo](https://user-images.githubusercontent.com/44510312/107421058-d5305100-6b19-11eb-8fcf-8e07fb7e76a6.png)
You can't silence me :)
I'll always be lurking around.

**Comment by B2H990** [comment]
> Now, A2H, why do you feel that you are being "forced" to use this, rather than have the pleasure to?

because it's not kotlin

**Comment by B2H990** [comment]
and It's scary

**Comment by B2H990** [comment]
asm is a hard word to say

**Comment by ghost** [comment]
> because it's not kotlin

don't worry, i will do my best to allow for compatibility with all JVM languages, as long as i don't have to do any work to add support :)

**Comment by ghost** [comment]
> asm is a hard word to say

you don't have to use ASM, don't worry about it, just use the abstraction and you don't have to touch it hopefully

**Comment by B2H990** [comment]
yes but the word is scary

**Comment by SWP360** [comment]
cry more idiot, we hate kotlin.

**Comment by charlie353535** [comment]
@B2H990 the package name is xyz.charlie35 is it not :>

**Comment by ghost** [comment]
i'll close this now
